version: "2"
services:
  app:
    container_name: app
    restart: always
    build: ./app
    ports:
      - "80:80"
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
  mongo_data:
    container_name: mongo_data
    image: mongo
    depends_on:
      - app
      - mongo
    volumes:
      - ./mongo:/mongo
    command:
      sh ./mongo/import.sh
